// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwldJes_1dWER_-lFEsZk9z52KPh1-Wzk',
    appId: '1:926550624136:web:209807ace82ca595e35c3d',
    messagingSenderId: '926550624136',
    projectId: 'chat-app-1ae7a',
    authDomain: 'chat-app-1ae7a.firebaseapp.com',
    storageBucket: 'chat-app-1ae7a.firebasestorage.app',
    measurementId: 'G-XTN7RW9XYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkFjdB8_Abr1Nz4R_IyskBwUhjsNfGIhw',
    appId: '1:926550624136:android:7242212f6206d6e8e35c3d',
    messagingSenderId: '926550624136',
    projectId: 'chat-app-1ae7a',
    storageBucket: 'chat-app-1ae7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDReGteuIAJLie_A7E8M6jYNMc8CZiSf2E',
    appId: '1:926550624136:ios:e8a504e7c7185df4e35c3d',
    messagingSenderId: '926550624136',
    projectId: 'chat-app-1ae7a',
    storageBucket: 'chat-app-1ae7a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDReGteuIAJLie_A7E8M6jYNMc8CZiSf2E',
    appId: '1:926550624136:ios:e8a504e7c7185df4e35c3d',
    messagingSenderId: '926550624136',
    projectId: 'chat-app-1ae7a',
    storageBucket: 'chat-app-1ae7a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwldJes_1dWER_-lFEsZk9z52KPh1-Wzk',
    appId: '1:926550624136:web:b280ecfcdefb72bbe35c3d',
    messagingSenderId: '926550624136',
    projectId: 'chat-app-1ae7a',
    authDomain: 'chat-app-1ae7a.firebaseapp.com',
    storageBucket: 'chat-app-1ae7a.firebasestorage.app',
    measurementId: 'G-0W1H2B5VDQ',
  );
}
